package com.sn.googleplace.GooglePlacesAPI.Constant;

/**
 * Created by parag.chauhan on 7/30/2015.
 */
public class GooglePlace_API_Constant {
     //Required Parameter
    //For Near By KEY ,LOCATION,RADIUS
    //For textSearch api only QUERY and KEY
    //For RadarSearch KEY , LOCATION , RADIUS and at least one of keyword, name, or types
    //For Place Details KEY ,PLACEID
    //For AutoComplete input,key

    public static String KEY = "key", QUERY = "query", PLACEID = "placeid" ,INPUT = "input";
    public static String LONGITUDE = "longitude", LATITUDE = "latitude", LOCATION = "location";
    public static String RADIUS = "radius";


    //Optional Parameter
    public static String KEYWORD = "keyword", LANGUAGE = "language";
    public static String MINPRICE = "minprice", NAME = "name", MAXPRICE = "maxprice", OPENNOW = "opennow", TYPES = "types", ZAGATSELECTED = "zagatselected";

    public class Price {
        // 0 means 4 means price low to high
        public String ZERO = "0", ONE = "1", TWO = "2", THREE = "3", FOUR = "4";
    }

    public static class Types {
        //you can apply multiple using pipe symbol (type1|type2|etc).
        public static String ACCOUNTING = "accounting",
                AIRPORT = "airport",
                AMUSEMENT_PARK = "amusement_park",
                AQUARIUM = "aquarium",
                ART_GALLERY = "art_gallery",
                ATM = "atm",
                BAKERY = "bakery",
                BANK = "bank",
                BAR = "bar",
                BEAUTY_SALON = "beauty_salon",
                BICYCLE_STORE = "bicycle_store",
                BOOK_STORE = "book_store",
                BOWLING_ALLEY = "bowling_alley",
                BUS_STATION = "bus_station",
                CAFE = "cafe",
                CAMPGROUND = "campground",
                CAR_DEALER = "car_dealer",
                CAR_RENTAL = "car_rental",
                CAR_REPAIR = "car_repair",
                CAR_WASH = "car_wash",
                CASINO = "casino",
                CEMETERY = "cemetery",
                CHURCH = "church",
                CITY_HALL = "city_hall",
                CLOTHING_STORE = "clothing_store",
                CONVENIENCE_STORE = "convenience_store",
                COURTHOUSE = "courthouse",
                DENTIST = "dentist",
                DEPARTMENT_STORE = "department_store",
                DOCTOR = "doctor",
                ELECTRICIAN = "electrician",
                ELECTRONICS_STORE = "electronics_store",
                EMBASSY = "embassy",
                ESTABLISHMENT = "establishment",
                FINANCE = "finance",
                FIRE_STATION = "fire_station",
                FLORIST = "florist",
                FOOD = "food",
                FUNERAL_HOME = "funeral_home",
                FURNITURE_STORE = "furniture_store",
                GAS_STATION = "gas_station",
                GENERAL_CONTRACTOR = "general_contractor",
                GROCERY_OR_SUPERMARKET = "grocery_or_supermarket",
                GYM = "gym",
                HAIR_CARE = "hair_care",
                HARDWARE_STORE = "hardware_store",
                HEALTH = "health",
                HINDU_TEMPLE = "hindu_temple",
                HOME_GOODS_STORE = "home_goods_store",
                HOSPITAL = "hospital",
                INSURANCE_AGENCY = "insurance_agency",
                JEWELRY_STORE = "jewelry_store",
                LAUNDRY = "laundry",
                LAWYER = "lawyer",
                LIBRARY = "library",
                LIQUOR_STORE = "liquor_store",
                LOCAL_GOVERNMENT_OFFICE = "local_government_office",
                LOCKSMITH = "locksmith",
                LODGING = "lodging",
                MEAL_DELIVERY = "meal_delivery",
                MEAL_TAKEAWAY = "meal_takeaway",
                MOSQUE = "mosque",
                MOVIE_RENTAL = "movie_rental",
                MOVIE_THEATER = "movie_theater",
                MOVING_COMPANY = "moving_company",
                MUSEUM = "museum",
                NIGHT_CLUB = "night_club",
                PAINTER = "painter",
                PARK = "park",
                PARKING = "parking",
                PET_STORE = "pet_store",
                PHARMACY = "pharmacy",
                PHYSIOTHERAPIST = "physiotherapist",
                PLACE_OF_WORSHIP = "place_of_worship",
                PLUMBER = "plumber",
                POLICE = "police",
                POST_OFFICE = "post_office",
                REAL_ESTATE_AGENCY = "real_estate_agency",
                RESTAURANT = "restaurant",
                ROOFING_CONTRACTOR = "roofing_contractor",
                RV_PARK = "rv_park",
                SCHOOL = "school",
                SHOE_STORE = "shoe_store",
                SHOPPING_MALL = "shopping_mall",
                SPA = "spa",
                STADIUM = "stadium",
                STORAGE = "storage",
                STORE = "store",
                SUBWAY_STATION = "subway_station",
                SYNAGOGUE = "synagogue",
                TAXI_STAND = "taxi_stand",
                TRAIN_STATION = "train_station",
                TRAVEL_AGENCY = "travel_agency",
                UNIVERSITY = "university",
                VETERINARY_CARE = "veterinary_care",
                ZOO = "zoo",
                ADMINISTRATIVE_AREA_LEVEL_1 = "administrative_area_level_1",
                ADMINISTRATIVE_AREA_LEVEL_2 = "administrative_area_level_2",
                ADMINISTRATIVE_AREA_LEVEL_3 = "administrative_area_level_3",
                ADMINISTRATIVE_AREA_LEVEL_4 = "administrative_area_level_4",
                ADMINISTRATIVE_AREA_LEVEL_5 = "administrative_area_level_5",
                COLLOQUIAL_AREA = "colloquial_area",
                COUNTRY = "country",
                FLOOR = "floor",
                GEOCODE = "geocode",
                INTERSECTION = "intersection",
                LOCALITY = "locality",
                NATURAL_FEATURE = "natural_feature",
                NEIGHBORHOOD = "neighborhood",
                POLITICAL = "political",
                POINT_OF_INTEREST = "point_of_interest",
                POST_BOX = "post_box",
                POSTAL_CODE = "postal_code",
                POSTAL_CODE_PREFIX = "postal_code_prefix",
                POSTAL_CODE_SUFFIX = "postal_code_suffix",
                POSTAL_TOWN = "postal_town",
                PREMISE = "premise",
                ROOM = "room",
                ROUTE = "route",
                STREET_ADDRESS = "street_address",
                STREET_NUMBER = "street_number",
                SUBLOCALITY = "sublocality",
                SUBLOCALITY_LEVEL_4 = "sublocality_level_4",
                SUBLOCALITY_LEVEL_5 = "sublocality_level_5",
                SUBLOCALITY_LEVEL_3 = "sublocality_level_3",
                SUBLOCALITY_LEVEL_2 = "sublocality_level_2",
                SUBLOCALITY_LEVEL_1 = "sublocality_level_1",
                SUBPREMISE = "subpremise",
                TRANSIT_STATION = "transit_station";
    }

    public static class Languages {
        public static String ARABIC = "ar",
                BASQUE = "eu",
                BULGARIAN = "bg",
                BENGALI = "bn",
                CATALAN = "ca",
                CZECH = "cs",
                DANISH = "da",
                GERMAN = "de",
                GREEK = "el",
                ENGLISH = "en",
                ENGLISH_AUSTRALIAN = "en-AU",
                ENGLISH_GREAT_BRITAIN = "en-GB",
                SPANISH = "es",
                FARSI = "fa",
                FINNISH = "fi",
                FILIPINO = "fil",
                FRENCH = "fr",
                GALICIAN = "gl",
                GUJARATI = "gu",
                HINDI = "hi",
                CROATIAN = "hr",
                HUNGARIAN = "hu",
                INDONESIAN = "id",
                ITALIAN = "it",
                HEBREW = "iw",
                JAPANESE = "ja",
                KANNADA = "kn",
                KOREAN = "ko",
                LITHUANIAN = "lt",
                LATVIAN = "lv",
                MALAYALAM = "ml",
                MARATHI = "mr",
                DUTCH = "nl",
                NORWEGIAN = "no",
                POLISH = "pl",
                PORTUGUESE = "pt",
                PORTUGUESE_BRAZIL = "pt-BR",
                PORTUGUESE_PORTUGAL = "pt-PT",
                ROMANIAN = "ro",
                RUSSIAN = "ru",
                SLOVAK = "sk",
                SLOVENIAN = "sl",
                SERBIAN = "sr",
                SWEDISH = "sv",
                TAGALOG = "tl",
                TAMIL = "ta",
                TELUGU = "te",
                THAI = "th",
                TURKISH = "tr",
                UKRAINIAN = "uk",
                VIETNAMESE = "vi",
                CHINESE_SIMPLIFIED = "zh-CN",
                CHINESE_TRADITIONAL = "zh-TW";
    }

}
